sudo: required
services:
    - docker

before_install:
    - docker build -t jonbelinfante/docker-complex -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true jonbelinfante/docker-react npm run test

    

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-982521910771"
  bucker_path: "docker-react"
  on:
     branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
